### PR TITLE
Fix typo: `aquire` -> `acquire`

### PR DESCRIPTION
**Pull request by guihkx**

### CODE REVIEW

**Comment by razzeee** [comment]
I think this should only touch the tsx and the english json file. Otherwise, we might get conflicts / missed translations otherwise.

**Comment by guihkx** [comment]
I don't see how that would happen, but then again I'm not familiar with the codebase.

So, should I keep the typo in the name of the property (i.e. `can-aquire-arbitrary-permissions`)?

**Comment by razzeee** [comment]
No, you can change it, but only in the common.json for `en`. Our translation system will then drop all non matching keys.

**Comment by razzeee** [comment]
Thanks for working on this

**Pull request merged**
