### PR TITLE
Change login flow handling to prevent 400 errors

### PR DESCRIPTION
**Pull request by ajr0d**
Spun up a quick fix (attempt) at what was pointed out on #241. I'm second guessing the fix however, as I'm not sure if and when the `else` statement would happen. Any improvements, please let me know and I'll add them.

### CODE REVIEW

**Review by kymckay — CHANGES_REQUESTED** [review]
I don't think this is right, the actual error returned in this case seems intentional, from my reading of the code this change should result in no visible behaviour difference (the while loop will either break or hit function return - where break is effectively the same as pass from the if statement).

To meet expected user behaviour we probably need to rework the backend logic to do something other than return an error in the case that the user is mid-flow elsewhere.

**Comment by ajr0d** [comment]
> I don't think this is right, the actual error returned in this case seems intentional, from my reading of the code this change should result in no visible behaviour difference (the while loop will either break or hit function return - where break is effectively the same as pass from the if statement).

This is does have a behaviour change, it now lets the user click Google, hit back and use GitLab (and vice versa).  Before, it would keep doing that "400 Bad Request".  I agree with that the actual error is intentional, but I'm not sure in which cases it should happen.

>To meet expected user behaviour we probably need to rework the backend logic to do something other than return an error in the case that the user is mid-flow elsewhere.

I also initially thought this, and that's why I opted for a `while` loop as I thought there could be a way inside the `else` to loop to the top of the `while` statement, but that's obviously not happening so I'm at a bit of a loss of what would be a more approriate workaround while keeping the error.

**Comment by kymckay** [comment]
> This is does have a behaviour change, it now lets the user click Google, hit back and use GitLab (and vice versa). Before, it would keep doing that "400 Bad Request". I agree with that the actual error is intentional, but I'm not sure in which cases it should happen.

I see, I had overlooked that the login dict's method is being assigned and forced to match the method passed as an argument. In that case, in terms of the local logic:

- The `if` branch is unnecessary since it will always be true.
- The `else` branch is unreachable.
- The `while` seems unnecessary because the logic will always break (if `else` was reachable it would break or return) from the loop on the first iteration. It's also unclear why the loop would be necessary if this weren't the case.

In terms of the wider logic my review process is:

1. I need to check if modifying the dict like this is safe as far as the caller is concerned. It smells of an antipattern.
2. The dict is coming from the login state, which looks to be given as an rvalue (for lack of a more Pythonic term) so it's safe to modify.
3. However, by modifying it we're locally overriding the true `"active-login-flow"` retrieved, which seems hacky and like it could have unintended consequences.

It seems to me like the proper way to resolve this is to make sure if already logging in, we just clean that up and then initiate the new flow. That may be what this change is achieving (I'm not super familiar with the rest of the logic that follows in this method), but it's unclear from the code change / justification given here.

**Comment by danielsilverstone-ct** [comment]
We'll close this because it's not ideal as an approach and we should reconsider how to achieve the goals.  Thanks for your attempt though.

**Pull request closed without merging**
