### PR TITLE
feat(frontend): use modal for deletion confirmation

### PR DESCRIPTION
**Pull request by kymckay**
This PR actually makes the confirmation dialog component use Headless UI's modal component which brings all the benefits of:

- Adding a transition
- Built-in accessibility attributes and navigation
- Inherently using a React portal to render on top of the page and easily centre the dialog

I also moved the account deletion button to the bottom of the user page since it's a one-time action that doesn't contribute to user convenience by being immediately available at the top of the page (and associated with the other actions there).

New deletion button location:
Screenshot from 2022-06-17 18-39-58

Modal dialog in action:
Screenshot from 2022-06-17 18-40-10

### CODE REVIEW

**Comment by razzeee** [comment]
I think we want the modal to have a lot more spacing, especially outer spacing

**Comment by kymckay** [comment]
More spacing, using dialog title for prompt and replaced the border with some medium shadow:

image

**Comment by razzeee** [comment]
I've pushed another improvement. I'm also kind of wondering, if I would prefer the delete account to be on the right and not on the left

**Comment by kymckay** [comment]
I just did some quick UX research to see if button order is noted as significant anywhere, but doesn't seem to be so no objections from me to switching that around :+1: (everything I did find we seem to be doing well here)

Pretty sure I originally put them in that order just for consistency with some other modals I checked, but I see that Youtube has them reversed for example so that's not a widespread standard.

**Comment by razzeee** [comment]
I think that makes sense

**Pull request merged**
