### PR TITLE
Keep download stats on rebase

### PR DESCRIPTION
**Pull request by JakobDev**
If a App changes the ID, it has no all download stats from the previous ID

### CODE REVIEW

**Comment by razzeee** [comment]
@barthalion do we actually want this?

**Comment by JakobDev** [comment]
I personally think, if a App is rebased, it just means the ID is changed. So all data (except verification) should be transferred to the new ID.

**Comment by barthalion** [comment]
No strong opinion on this from me.

**Comment by razzeee** [comment]
> I personally think, if a App is rebased, it just means the ID is changed. So all data (except verification) should be transferred to the new ID.

Makes me wonder, if vending should be transfered, that might in fact be wanted or not, depending on the case

**Pull request merged**
