### PR TITLE
Add storybook and some examples

### PR DESCRIPTION
**Pull request by razzeee**
This also adds faker for nicer creation of test data

### CODE REVIEW

**Comment by kymckay** [comment]
Interestingly this works, but I see a lot of error output about broken build due to unresolved models in the terminal.

> ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../flathub/frontend/node_modules/next-i18next/dist/esm/config'

**Review by kymckay — COMMENTED** [review]
Interestingly this works, but I see a lot of error output about broken build due to unresolved models in the terminal.

> ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../flathub/frontend/node_modules/next-i18next/dist/esm/config'

**Comment by razzeee** [comment]
Yeah, I've seen that and investigated it a bit, but didn't feel like it was worth investing more time in.

**Comment by razzeee** [comment]
Tracked the error down and fixed it.

There also was a different one with the a11y plugin, I've removed that for now.

**Pull request merged**
