### PR TITLE
Darken main color for dark mode

### PR DESCRIPTION
**Pull request by razzeee**
Closes https://github.com/flathub/website/issues/109

### CODE REVIEW

**Comment by razzeee** [comment]
@jimmac

**Comment by jimmac** [comment]
I'd love to get more involved and do reviews/contribute. I tried setting up the website locally, but couldn't make it work, sadly. Screenshots is the only way, I'm afraid.

**Comment by razzeee** [comment]
Sorry I've missed your response in the issue somehow :(

But it would be interesting, why you couldn't make it work on your system, as I want the readme to be able to guide anyone through that.

**Comment by razzeee** [comment]
A darker one

image

image

**Comment by jimmac** [comment]
This works for the header 👍. 

I'd separate the buttons and give them more contrast vs the background (the old blue worked there ;)

**Comment by razzeee** [comment]
Which button are you talking about the primary (`more` for e.g.) or the secondary `quick setup` or do you mean both?

image

Small change in the screenshot as the secondary button previously had both blue

**Comment by jimmac** [comment]
> Which button are you talking about the primary (`more` for e.g.) or the secondary `quick setup` or do you mean both?

Both will benefit from stronger contrast. The original issue was about the large background spaces rather than individual controls. Having a single color property sounds nice and consistent, but perhaps deriving one from the other (value, opacity shift) allows to hit both objectives.

**Comment by razzeee** [comment]
Let's merge this then and keep refining it? There are more places around the whole page, where this color change will show effects. Pretty hard to show, without actually using/deploying the page.

**Pull request merged**
