### PR TITLE
Add vcs-browser and contribute URL types

### PR DESCRIPTION
**Pull request by JakobDev**
This PR is the successor of #79

Flathub has now the first Apps which are using the new URL types. A example of a App which uses both new types, so you can test it, is io.qt.Linguist.

grafik

### CODE REVIEW

**Comment by razzeee** [comment]
LGTM, but needs formatting

**Comment by JakobDev** [comment]
@razzeee  What command should I run for auto formatting?

**Comment by razzeee** [comment]
`npm run format:fix` https://github.com/flathub/website/blob/main/frontend/package.json#L13

**Comment by JakobDev** [comment]
I have now ran format:fix.

**Comment by razzeee** [comment]
Thank you

**Pull request merged**
