### PR TITLE
Update czech language

### PR DESCRIPTION
**Pull request by vikdevelop**

### CODE REVIEW

**Comment by razzeee** [comment]
Just making sure, are you aware, that the normal workflow would be to add these via https://hosted.weblate.org/engage/flathub/ ?

**Comment by vikdevelop** [comment]
> Just making sure, are you aware, that the normal workflow would be to add these via https://hosted.weblate.org/engage/flathub/ ?

I used weblate to translate FlatHub to Czech:
https://hosted.weblate.org/projects/flathub/frontend/cs/#overview
The website is now 88% translated.

**Comment by razzeee** [comment]
Thank you, let's continue in https://github.com/flathub/website/pull/173 then

**Comment by vikdevelop** [comment]
> Thank you, let's continue in https://github.com/flathub/website/pull/173 then

Why build is failed?

**Comment by razzeee** [comment]
We're trying to build the pages, but the backend seems to not be responsive right now, so that failed.

**Pull request closed without merging**
