### PR TITLE
Upgrade Python to 3.11

### PR DESCRIPTION
**Pull request by barthalion**
There's no stable Docker image yet for 3.11.0, so marking it as a draft to prevent accidental merge.

### CODE REVIEW

**Comment by razzeee** [comment]
We're waiting for https://github.com/aio-libs/yarl/issues/781 right now

**Comment by razzeee** [comment]
Dependencies seem to be up to date now, but one test fails for whatever reason.

**Comment by razzeee** [comment]
@barthalion should be ready now, for whenever you want to upgrade the server

**Comment by barthalion** [comment]
It's fine to merge it, it doesn't require anything from infra side. We directly use Dockerfile for deployments.

**Comment by razzeee** [comment]
But I thought infra has it's own config that's not related to ours?

**Comment by barthalion** [comment]
docker-compose is unrelated to the deployment, but the image being built by CI/CD in this repo is.

**Comment by razzeee** [comment]
Thanks for explaining

**Pull request merged**
